# Generated by Django 5.2 on 2026-02-26 04:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (case-insensitive)', max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount in percent (0–100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
