# Generated by Django 5.2 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount_amount_alter_order_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time',
            field=models.DecimalField(decimal_places=2, help_text='Price of the item when the order was placed', max_digits=10),
        ),
    ]
